[2021-07-03 17:54:22,830] {_internal.py:225} WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-07-03 17:54:22,831] {_internal.py:225} INFO -  * Running on http://192.168.1.9:666/ (Press CTRL+C to quit)
[2021-07-03 17:54:39,066] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 17:54:39] "GET /api/ HTTP/1.1" 200 -
[2021-07-03 17:54:39,417] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 17:54:39] "[36mGET /api/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 -
[2021-07-03 17:54:39,418] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 17:54:39] "[36mGET /api/swagger-ui-bundle.js HTTP/1.1[0m" 304 -
[2021-07-03 17:54:39,419] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 17:54:39] "[36mGET /api/swagger-ui.css HTTP/1.1[0m" 304 -
[2021-07-03 17:54:39,616] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 17:54:39] "[36mGET /static/swagger.json HTTP/1.1[0m" 304 -
[2021-07-03 17:54:39,623] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 17:54:39] "[36mGET /api/favicon-32x32.png HTTP/1.1[0m" 304 -
[2021-07-03 17:56:22,677] {database.py:29} INFO - Database Connected..........
[2021-07-03 17:56:22,678] {ftl.py:74} INFO - getFTL() Called.........
[2021-07-03 17:56:22,679] {database.py:39} INFO - Database Connection Closed.........
[2021-07-03 17:56:22,700] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 17:56:22] "GET /api/v1/ftl HTTP/1.1" 200 -
[2021-07-03 18:12:47,044] {_internal.py:225} WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-07-03 18:12:47,046] {_internal.py:225} INFO -  * Running on http://192.168.1.9:666/ (Press CTRL+C to quit)
[2021-07-03 18:12:49,741] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 18:12:49] "GET /api/ HTTP/1.1" 200 -
[2021-07-03 18:12:50,095] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 18:12:50] "[36mGET /api/swagger-ui.css HTTP/1.1[0m" 304 -
[2021-07-03 18:12:50,096] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 18:12:50] "[36mGET /api/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 -
[2021-07-03 18:12:50,097] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 18:12:50] "[36mGET /api/swagger-ui-bundle.js HTTP/1.1[0m" 304 -
[2021-07-03 18:12:50,279] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 18:12:50] "[36mGET /static/swagger.json HTTP/1.1[0m" 304 -
[2021-07-03 18:12:50,320] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 18:12:50] "[36mGET /api/favicon-32x32.png HTTP/1.1[0m" 304 -
[2021-07-03 20:43:03,000] {_internal.py:225} WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-07-03 20:43:03,003] {_internal.py:225} INFO -  * Running on http://192.168.1.9:666/ (Press CTRL+C to quit)
[2021-07-03 20:43:11,555] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:43:11] "[32mGET / HTTP/1.1[0m" 302 -
[2021-07-03 20:43:11,577] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:43:11] "GET /api/ HTTP/1.1" 200 -
[2021-07-03 20:43:12,016] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:43:12] "[36mGET /api/swagger-ui.css HTTP/1.1[0m" 304 -
[2021-07-03 20:43:12,017] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:43:12] "[36mGET /api/swagger-ui-bundle.js HTTP/1.1[0m" 304 -
[2021-07-03 20:43:12,018] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:43:12] "[36mGET /api/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 -
[2021-07-03 20:43:12,212] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:43:12] "[33mGET /static/swagger.json HTTP/1.1[0m" 404 -
[2021-07-03 20:44:29,687] {_internal.py:225} WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-07-03 20:44:29,688] {_internal.py:225} INFO -  * Running on http://192.168.1.9:666/ (Press CTRL+C to quit)
[2021-07-03 20:44:42,446] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:44:42] "[32mGET / HTTP/1.1[0m" 302 -
[2021-07-03 20:44:42,453] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:44:42] "[32mGET /api HTTP/1.1[0m" 308 -
[2021-07-03 20:44:42,468] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:44:42] "GET /api/ HTTP/1.1" 200 -
[2021-07-03 20:44:42,848] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:44:42] "GET /api/swagger-ui.css HTTP/1.1" 200 -
[2021-07-03 20:44:42,848] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:44:42] "GET /api/swagger-ui-standalone-preset.js HTTP/1.1" 200 -
[2021-07-03 20:44:42,848] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:44:42] "GET /api/swagger-ui-bundle.js HTTP/1.1" 200 -
[2021-07-03 20:44:43,032] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:44:43] "[33mGET /api/static/swagger.json HTTP/1.1[0m" 404 -
[2021-07-03 20:44:43,072] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:44:43] "GET /api/favicon-32x32.png HTTP/1.1" 200 -
[2021-07-03 20:45:27,951] {_internal.py:225} WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-07-03 20:45:27,952] {_internal.py:225} INFO -  * Running on http://192.168.1.9:666/ (Press CTRL+C to quit)
[2021-07-03 20:45:30,785] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:45:30] "GET /api/ HTTP/1.1" 200 -
[2021-07-03 20:45:31,127] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:45:31] "[36mGET /api/swagger-ui.css HTTP/1.1[0m" 304 -
[2021-07-03 20:45:31,128] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:45:31] "[36mGET /api/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 -
[2021-07-03 20:45:31,128] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:45:31] "[36mGET /api/swagger-ui-bundle.js HTTP/1.1[0m" 304 -
[2021-07-03 20:45:31,235] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:45:31] "[33mGET /static/swagger.json HTTP/1.1[0m" 404 -
[2021-07-03 20:45:31,240] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:45:31] "GET /api/favicon-32x32.png HTTP/1.1" 200 -
[2021-07-03 20:47:41,988] {_internal.py:225} WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-07-03 20:47:41,989] {_internal.py:225} INFO -  * Running on http://192.168.1.9:666/ (Press CTRL+C to quit)
[2021-07-03 20:47:46,673] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:47:46] "GET /api/ HTTP/1.1" 200 -
[2021-07-03 20:47:47,009] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:47:47] "[36mGET /api/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 -
[2021-07-03 20:47:47,009] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:47:47] "[36mGET /api/swagger-ui.css HTTP/1.1[0m" 304 -
[2021-07-03 20:47:47,010] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:47:47] "[36mGET /api/swagger-ui-bundle.js HTTP/1.1[0m" 304 -
[2021-07-03 20:47:47,092] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:47:47] "GET /static/swagger.json HTTP/1.1" 200 -
[2021-07-03 20:47:47,095] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:47:47] "GET /api/favicon-32x32.png HTTP/1.1" 200 -
[2021-07-03 20:49:04,513] {database.py:29} INFO - Database Connected..........
[2021-07-03 20:49:04,514] {elevate.py:19} INFO - getConfig() Called.........
[2021-07-03 20:49:04,515] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:49:04] "[31m[1mGET /api/v1/elevate/config HTTP/1.1[0m" 401 -
[2021-07-03 20:56:10,575] {_internal.py:225} WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-07-03 20:56:10,576] {_internal.py:225} INFO -  * Running on http://192.168.1.9:666/ (Press CTRL+C to quit)
[2021-07-03 20:56:14,550] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:56:14] "GET /api/ HTTP/1.1" 200 -
[2021-07-03 20:56:14,879] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:56:14] "[36mGET /api/swagger-ui-bundle.js HTTP/1.1[0m" 304 -
[2021-07-03 20:56:14,880] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:56:14] "[36mGET /api/swagger-ui.css HTTP/1.1[0m" 304 -
[2021-07-03 20:56:14,881] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:56:14] "[36mGET /api/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 -
[2021-07-03 20:56:15,067] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:56:15] "[36mGET /static/swagger.json HTTP/1.1[0m" 304 -
[2021-07-03 20:56:15,071] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:56:15] "[36mGET /api/favicon-32x32.png HTTP/1.1[0m" 304 -
[2021-07-03 20:56:22,807] {database.py:29} INFO - Database Connected..........
[2021-07-03 20:56:22,808] {ftl.py:74} INFO - getFTL() Called.........
[2021-07-03 20:56:22,813] {database.py:39} INFO - Database Connection Closed.........
[2021-07-03 20:56:22,815] {_internal.py:225} INFO - 192.168.1.9 - - [03/Jul/2021 20:56:22] "GET /api/v1/ftl HTTP/1.1" 200 -
[2021-07-04 04:34:58,136] {_internal.py:225} WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-07-04 04:34:58,138] {_internal.py:225} INFO -  * Running on http://192.168.1.9:666/ (Press CTRL+C to quit)
[2021-07-04 04:35:07,392] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:35:07] "[32mGET / HTTP/1.1[0m" 302 -
[2021-07-04 04:35:07,421] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:35:07] "GET /api/ HTTP/1.1" 200 -
[2021-07-04 04:35:07,951] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:35:07] "[36mGET /api/swagger-ui.css HTTP/1.1[0m" 304 -
[2021-07-04 04:35:07,963] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:35:07] "[36mGET /api/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 -
[2021-07-04 04:35:07,966] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:35:07] "[36mGET /api/swagger-ui-bundle.js HTTP/1.1[0m" 304 -
[2021-07-04 04:35:08,147] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:35:08] "GET /static/swagger.json HTTP/1.1" 200 -
[2021-07-04 04:38:47,796] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:38:47] "GET /api/ HTTP/1.1" 200 -
[2021-07-04 04:38:47,830] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:38:47] "[36mGET /api/swagger-ui.css HTTP/1.1[0m" 304 -
[2021-07-04 04:38:47,833] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:38:47] "[36mGET /api/swagger-ui-bundle.js HTTP/1.1[0m" 304 -
[2021-07-04 04:38:47,836] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:38:47] "[36mGET /api/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 -
[2021-07-04 04:38:48,045] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:38:48] "GET /static/swagger.json HTTP/1.1" 200 -
[2021-07-04 04:38:48,062] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:38:48] "GET /api/favicon-32x32.png HTTP/1.1" 200 -
[2021-07-04 04:43:36,027] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:43:36] "GET /api/ HTTP/1.1" 200 -
[2021-07-04 04:43:36,083] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:43:36] "[36mGET /api/swagger-ui.css HTTP/1.1[0m" 304 -
[2021-07-04 04:43:36,083] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:43:36] "[36mGET /api/swagger-ui-bundle.js HTTP/1.1[0m" 304 -
[2021-07-04 04:43:36,085] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:43:36] "[36mGET /api/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 -
[2021-07-04 04:43:36,292] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:43:36] "GET /static/swagger.json HTTP/1.1" 200 -
[2021-07-04 04:43:36,302] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:43:36] "GET /api/favicon-32x32.png HTTP/1.1" 200 -
[2021-07-04 04:46:12,133] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:46:12] "GET /api/ HTTP/1.1" 200 -
[2021-07-04 04:46:12,157] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:46:12] "[36mGET /api/swagger-ui.css HTTP/1.1[0m" 304 -
[2021-07-04 04:46:12,158] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:46:12] "[36mGET /api/swagger-ui-bundle.js HTTP/1.1[0m" 304 -
[2021-07-04 04:46:12,162] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:46:12] "[36mGET /api/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 -
[2021-07-04 04:46:12,265] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:46:12] "GET /static/swagger.json HTTP/1.1" 200 -
[2021-07-04 04:46:12,277] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:46:12] "GET /api/favicon-32x32.png HTTP/1.1" 200 -
[2021-07-04 04:47:51,560] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:47:51] "[32mGET / HTTP/1.1[0m" 302 -
[2021-07-04 04:47:51,581] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:47:51] "GET /api/ HTTP/1.1" 200 -
[2021-07-04 04:47:51,645] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:47:51] "[36mGET /api/swagger-ui.css HTTP/1.1[0m" 304 -
[2021-07-04 04:47:51,647] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:47:51] "[36mGET /api/swagger-ui-bundle.js HTTP/1.1[0m" 304 -
[2021-07-04 04:47:51,649] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:47:51] "[36mGET /api/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 -
[2021-07-04 04:47:52,277] {_internal.py:225} INFO - 192.168.1.9 - - [04/Jul/2021 04:47:52] "GET /static/swagger.json HTTP/1.1" 200 -
[2021-07-06 07:17:28,178] {_internal.py:225} WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-07-06 07:17:28,279] {_internal.py:225} INFO -  * Running on http://192.168.1.243:666/ (Press CTRL+C to quit)
[2021-07-06 07:17:56,479] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:17:56] "[32mGET / HTTP/1.1[0m" 302 -
[2021-07-06 07:17:56,492] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:17:56] "[32mGET /api HTTP/1.1[0m" 308 -
[2021-07-06 07:17:56,535] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:17:56] "GET /api/ HTTP/1.1" 200 -
[2021-07-06 07:17:57,000] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:17:57] "GET /api/swagger-ui.css HTTP/1.1" 200 -
[2021-07-06 07:17:57,104] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:17:57] "GET /api/swagger-ui-bundle.js HTTP/1.1" 200 -
[2021-07-06 07:17:57,120] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:17:57] "GET /api/swagger-ui-standalone-preset.js HTTP/1.1" 200 -
[2021-07-06 07:17:57,293] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:17:57] "GET /static/swagger.json HTTP/1.1" 200 -
[2021-07-06 07:17:57,350] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:17:57] "GET /api/favicon-32x32.png HTTP/1.1" 200 -
[2021-07-06 07:18:13,953] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:18:13] "POST /api/v1/signin?password=Wayward1240 HTTP/1.1" 200 -
[2021-07-06 07:20:02,826] {app.py:1454} ERROR - Exception on /api/v1/signout [POST]
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\jwt\api_jws.py", line 187, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python39\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "e:\acumen-flask\v1\auth.py", line 39, in Signout
    if isTokenValid(request.args.get('token')):
  File "e:\acumen-flask\v1\auth.py", line 73, in isTokenValid
    decodedValue = decodetoken(token)
  File "e:\acumen-flask\v1\auth.py", line 101, in decodetoken
    decoded = jwt.decode(token, getPyConfig()['jwt-secret'], algorithms=["HS256"])
  File "C:\Python39\lib\site-packages\jwt\api_jwt.py", line 119, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "C:\Python39\lib\site-packages\jwt\api_jwt.py", line 90, in decode_complete
    decoded = api_jws.decode_complete(
  File "C:\Python39\lib\site-packages\jwt\api_jws.py", line 146, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
  File "C:\Python39\lib\site-packages\jwt\api_jws.py", line 190, in _load
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments
[2021-07-06 07:20:02,844] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:20:02] "[35m[1mPOST /api/v1/signout?token=TMC6FGOU6VC4ZL1MO2GQJR9CTR5LMBYO0MUAGCIL6LB27SBAAF HTTP/1.1[0m" 500 -
[2021-07-06 07:20:53,685] {app.py:1454} ERROR - Exception on /api/v1/signout [POST]
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python39\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "e:\acumen-flask\v1\auth.py", line 39, in Signout
    if isTokenValid(request.args.get('token')):
  File "e:\acumen-flask\v1\auth.py", line 74, in isTokenValid
    if isinstance(decodedValue, types.StringType) == False:
AttributeError: module 'types' has no attribute 'StringType'
[2021-07-06 07:20:53,689] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:20:53] "[35m[1mPOST /api/v1/signout?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBJZCI6IlRNQzZGR09VNlZDNFpMMU1PMkdRSlI5Q1RSNUxNQllPME1VQUdDSUw2TEIyN1NCQUFGIiwiZXhwIjoxNjI1NTM3ODkzLjk1MjIzNywiaWF0IjoxNjI1NTM2MDkzLjk1MjIzN30.rSp11yG2XPBycE9U5rK7nl1QuF1p-3WVTinkGwSf6fA HTTP/1.1[0m" 500 -
[2021-07-06 07:21:01,406] {app.py:1454} ERROR - Exception on /api/v1/signout [POST]
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python39\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "e:\acumen-flask\v1\auth.py", line 39, in Signout
    if isTokenValid(request.args.get('token')):
  File "e:\acumen-flask\v1\auth.py", line 74, in isTokenValid
    if isinstance(decodedValue, types.StringType) == False:
AttributeError: module 'types' has no attribute 'StringType'
[2021-07-06 07:21:01,413] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:21:01] "[35m[1mPOST /api/v1/signout?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBJZCI6IlRNQzZGR09VNlZDNFpMMU1PMkdRSlI5Q1RSNUxNQllPME1VQUdDSUw2TEIyN1NCQUFGIiwiZXhwIjoxNjI1NTM3ODkzLjk1MjIzNywiaWF0IjoxNjI1NTM2MDkzLjk1MjIzN30.rSp11yG2XPBycE9U5rK7nl1QuF1p-3WVTinkGwSf6fA HTTP/1.1[0m" 500 -
[2021-07-06 07:22:07,977] {_internal.py:225} WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-07-06 07:22:07,978] {_internal.py:225} INFO -  * Running on http://192.168.1.243:666/ (Press CTRL+C to quit)
[2021-07-06 07:22:13,025] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:22:13] "GET /api/ HTTP/1.1" 200 -
[2021-07-06 07:22:13,366] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:22:13] "[36mGET /api/swagger-ui.css HTTP/1.1[0m" 304 -
[2021-07-06 07:22:13,366] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:22:13] "[36mGET /api/swagger-ui-bundle.js HTTP/1.1[0m" 304 -
[2021-07-06 07:22:13,367] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:22:13] "[36mGET /api/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 -
[2021-07-06 07:22:13,560] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:22:13] "[36mGET /static/swagger.json HTTP/1.1[0m" 304 -
[2021-07-06 07:22:13,574] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:22:13] "[36mGET /api/favicon-32x32.png HTTP/1.1[0m" 304 -
[2021-07-06 07:22:26,759] {app.py:1454} ERROR - Exception on /api/v1/signout [POST]
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python39\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "e:\acumen-flask\v1\auth.py", line 39, in Signout
    if isTokenValid(request.args.get('token')):
  File "e:\acumen-flask\v1\auth.py", line 74, in isTokenValid
    if isinstance(decodedValue, types.string) == False:
AttributeError: module 'types' has no attribute 'string'
[2021-07-06 07:22:26,764] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:22:26] "[35m[1mPOST /api/v1/signout?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBJZCI6IlRNQzZGR09VNlZDNFpMMU1PMkdRSlI5Q1RSNUxNQllPME1VQUdDSUw2TEIyN1NCQUFGIiwiZXhwIjoxNjI1NTM3ODkzLjk1MjIzNywiaWF0IjoxNjI1NTM2MDkzLjk1MjIzN30.rSp11yG2XPBycE9U5rK7nl1QuF1p-3WVTinkGwSf6fA HTTP/1.1[0m" 500 -
[2021-07-06 07:23:43,448] {_internal.py:225} WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-07-06 07:23:43,449] {_internal.py:225} INFO -  * Running on http://192.168.1.243:666/ (Press CTRL+C to quit)
[2021-07-06 07:23:48,345] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:23:48] "[31m[1mPOST /api/v1/signout?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBJZCI6IlRNQzZGR09VNlZDNFpMMU1PMkdRSlI5Q1RSNUxNQllPME1VQUdDSUw2TEIyN1NCQUFGIiwiZXhwIjoxNjI1NTM3ODkzLjk1MjIzNywiaWF0IjoxNjI1NTM2MDkzLjk1MjIzN30.rSp11yG2XPBycE9U5rK7nl1QuF1p-3WVTinkGwSf6fA HTTP/1.1[0m" 401 -
[2021-07-06 07:24:45,151] {_internal.py:225} WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-07-06 07:24:45,152] {_internal.py:225} INFO -  * Running on http://192.168.1.243:666/ (Press CTRL+C to quit)
[2021-07-06 07:24:51,263] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:24:51] "[31m[1mPOST /api/v1/signout?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBJZCI6IlRNQzZGR09VNlZDNFpMMU1PMkdRSlI5Q1RSNUxNQllPME1VQUdDSUw2TEIyN1NCQUFGIiwiZXhwIjoxNjI1NTM3ODkzLjk1MjIzNywiaWF0IjoxNjI1NTM2MDkzLjk1MjIzN30.rSp11yG2XPBycE9U5rK7nl1QuF1p-3WVTinkGwSf6fA HTTP/1.1[0m" 401 -
[2021-07-06 07:25:43,345] {_internal.py:225} WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-07-06 07:25:43,346] {_internal.py:225} INFO -  * Running on http://192.168.1.243:666/ (Press CTRL+C to quit)
[2021-07-06 07:25:50,301] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:25:50] "[31m[1mPOST /api/v1/signout?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBJZCI6IlRNQzZGR09VNlZDNFpMMU1PMkdRSlI5Q1RSNUxNQllPME1VQUdDSUw2TEIyN1NCQUFGIiwiZXhwIjoxNjI1NTM3ODkzLjk1MjIzNywiaWF0IjoxNjI1NTM2MDkzLjk1MjIzN30.rSp11yG2XPBycE9U5rK7nl1QuF1p-3WVTinkGwSf6fA HTTP/1.1[0m" 401 -
[2021-07-06 07:27:20,793] {_internal.py:225} WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-07-06 07:27:20,794] {_internal.py:225} INFO -  * Running on http://192.168.1.243:666/ (Press CTRL+C to quit)
[2021-07-06 07:27:25,467] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:27:25] "[31m[1mPOST /api/v1/signout?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBJZCI6IlRNQzZGR09VNlZDNFpMMU1PMkdRSlI5Q1RSNUxNQllPME1VQUdDSUw2TEIyN1NCQUFGIiwiZXhwIjoxNjI1NTM3ODkzLjk1MjIzNywiaWF0IjoxNjI1NTM2MDkzLjk1MjIzN30.rSp11yG2XPBycE9U5rK7nl1QuF1p-3WVTinkGwSf6fA HTTP/1.1[0m" 401 -
[2021-07-06 07:28:01,680] {_internal.py:225} WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-07-06 07:28:01,681] {_internal.py:225} INFO -  * Running on http://192.168.1.243:666/ (Press CTRL+C to quit)
[2021-07-06 07:28:06,048] {app.py:1454} ERROR - Exception on /api/v1/signout [POST]
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python39\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "e:\acumen-flask\v1\auth.py", line 38, in Signout
    if isTokenValid(request.args.get('token')):
  File "e:\acumen-flask\v1\auth.py", line 73, in isTokenValid
    print(type(decodedValue) + isinstance(decodedValue, dict))
TypeError: unsupported operand type(s) for +: 'type' and 'bool'
[2021-07-06 07:28:06,057] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:28:06] "[35m[1mPOST /api/v1/signout?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBJZCI6IlRNQzZGR09VNlZDNFpMMU1PMkdRSlI5Q1RSNUxNQllPME1VQUdDSUw2TEIyN1NCQUFGIiwiZXhwIjoxNjI1NTM3ODkzLjk1MjIzNywiaWF0IjoxNjI1NTM2MDkzLjk1MjIzN30.rSp11yG2XPBycE9U5rK7nl1QuF1p-3WVTinkGwSf6fA HTTP/1.1[0m" 500 -
[2021-07-06 07:28:46,957] {_internal.py:225} WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-07-06 07:28:46,958] {_internal.py:225} INFO -  * Running on http://192.168.1.243:666/ (Press CTRL+C to quit)
[2021-07-06 07:28:50,453] {app.py:1454} ERROR - Exception on /api/v1/signout [POST]
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python39\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "e:\acumen-flask\v1\auth.py", line 38, in Signout
    if isTokenValid(request.args.get('token')):
  File "e:\acumen-flask\v1\auth.py", line 73, in isTokenValid
    print(type(decodedValue) + str(isinstance(decodedValue, dict)))
TypeError: unsupported operand type(s) for +: 'type' and 'str'
[2021-07-06 07:28:50,460] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:28:50] "[35m[1mPOST /api/v1/signout?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBJZCI6IlRNQzZGR09VNlZDNFpMMU1PMkdRSlI5Q1RSNUxNQllPME1VQUdDSUw2TEIyN1NCQUFGIiwiZXhwIjoxNjI1NTM3ODkzLjk1MjIzNywiaWF0IjoxNjI1NTM2MDkzLjk1MjIzN30.rSp11yG2XPBycE9U5rK7nl1QuF1p-3WVTinkGwSf6fA HTTP/1.1[0m" 500 -
[2021-07-06 07:29:27,277] {_internal.py:225} WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-07-06 07:29:27,278] {_internal.py:225} INFO -  * Running on http://192.168.1.243:666/ (Press CTRL+C to quit)
[2021-07-06 07:29:33,371] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:29:33] "[31m[1mPOST /api/v1/signout?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBJZCI6IlRNQzZGR09VNlZDNFpMMU1PMkdRSlI5Q1RSNUxNQllPME1VQUdDSUw2TEIyN1NCQUFGIiwiZXhwIjoxNjI1NTM3ODkzLjk1MjIzNywiaWF0IjoxNjI1NTM2MDkzLjk1MjIzN30.rSp11yG2XPBycE9U5rK7nl1QuF1p-3WVTinkGwSf6fA HTTP/1.1[0m" 401 -
[2021-07-06 07:29:58,494] {app.py:1454} ERROR - Exception on /api/v1/signout [POST]
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\jwt\api_jws.py", line 198, in _load
    header = json.loads(header_data)
  File "C:\Python39\lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 25: invalid continuation byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python39\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "e:\acumen-flask\v1\auth.py", line 38, in Signout
    if isTokenValid(request.args.get('token')):
  File "e:\acumen-flask\v1\auth.py", line 72, in isTokenValid
    decodedValue = decodetoken(token)
  File "e:\acumen-flask\v1\auth.py", line 101, in decodetoken
    decoded = jwt.decode(token, getPyConfig()['jwt-secret'], algorithms=["HS256"])
  File "C:\Python39\lib\site-packages\jwt\api_jwt.py", line 119, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "C:\Python39\lib\site-packages\jwt\api_jwt.py", line 90, in decode_complete
    decoded = api_jws.decode_complete(
  File "C:\Python39\lib\site-packages\jwt\api_jws.py", line 146, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
  File "C:\Python39\lib\site-packages\jwt\api_jws.py", line 200, in _load
    raise DecodeError("Invalid header string: %s" % e) from e
jwt.exceptions.DecodeError: Invalid header string: 'utf-8' codec can't decode byte 0xf3 in position 25: invalid continuation byte
[2021-07-06 07:29:58,522] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:29:58] "[35m[1mPOST /api/v1/signout?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1ffNiJ9.eyJhcHBJZCI6IlRNQzZGR09VNlZDNFpMMU1PMkdRSlI5Q1RSNUxNQllPME1VQUdDSUw2TEIyN1NCQUFGIiwiZXhwIjoxNjI1NTM3ODkzLjk1MjIzNywiaWF0IjoxNjI1NTM2MDkzLjk1MjIzN30.rSp11yG2XPBycE9U5rK7nl1QuF1p-3WVTinkGwSf6fA HTTP/1.1[0m" 500 -
[2021-07-06 07:30:49,032] {app.py:1454} ERROR - Exception on /api/v1/signout [POST]
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\jwt\api_jws.py", line 211, in _load
    signature = base64url_decode(crypto_segment)
  File "C:\Python39\lib\site-packages\jwt\utils.py", line 33, in base64url_decode
    return base64.urlsafe_b64decode(input)
  File "C:\Python39\lib\base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "C:\Python39\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (45) cannot be 1 more than a multiple of 4

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python39\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "e:\acumen-flask\v1\auth.py", line 38, in Signout
    if isTokenValid(request.args.get('token')):
  File "e:\acumen-flask\v1\auth.py", line 72, in isTokenValid
    decodedValue = decodetoken(token)
  File "e:\acumen-flask\v1\auth.py", line 101, in decodetoken
    decoded = jwt.decode(token, getPyConfig()['jwt-secret'], algorithms=["HS256"])
  File "C:\Python39\lib\site-packages\jwt\api_jwt.py", line 119, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "C:\Python39\lib\site-packages\jwt\api_jwt.py", line 90, in decode_complete
    decoded = api_jws.decode_complete(
  File "C:\Python39\lib\site-packages\jwt\api_jws.py", line 146, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
  File "C:\Python39\lib\site-packages\jwt\api_jws.py", line 213, in _load
    raise DecodeError("Invalid crypto padding") from err
jwt.exceptions.DecodeError: Invalid crypto padding
[2021-07-06 07:30:49,057] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:30:49] "[35m[1mPOST /api/v1/signout?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBJZCI6IlRNQzZGR09VNlZDNFpMMU1PMkdRSlI5Q1RSNUxNQllPME1VQUdDSUw2TEIyN1NCQUFGIiwiZXhwIjoxNjI1NTM3ODkzLjk1MjIzNywiaWF0IjoxNjI1NTM2MDkzLjk1MjIzN30.rSp11yG2XPBycE9U5rK7nl1QuF1p-3WVTinkGwSf6fAFG HTTP/1.1[0m" 500 -
[2021-07-06 07:31:37,350] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:31:37] "[31m[1mPOST /api/v1/signout?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBJZCI6IlRNQzZGR09VNlZDNFpMMU1PMkdRSlI5Q1RSNUxNQllPME1VQUdDSUw2TEIyN1NCQUFGIiwiZXhwIjoxNjI1NTM3ODkzLjk1MjIzNywiaWF0IjoxNjI1NTM2MDkzLjk1MjIzN30.rSp11yG2XPBycE9U5rK7nl1QuF1p-3WVTinkGwSf6fB HTTP/1.1[0m" 401 -
[2021-07-06 07:32:23,801] {_internal.py:225} WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-07-06 07:32:23,802] {_internal.py:225} INFO -  * Running on http://192.168.1.243:666/ (Press CTRL+C to quit)
[2021-07-06 07:32:40,380] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:32:40] "POST /api/v1/signin?password=Wayward1240 HTTP/1.1" 200 -
[2021-07-06 07:33:14,978] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:33:14] "POST /api/v1/signout?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBJZCI6IlJRMzY2UEo3S1M4WFYzVTdSWVJTNExYWDk0OTk4TEU0TkJQVVNMUzdNN0pER1ozRE8xIiwiZXhwIjoxNjI1NTM4NzYwLjM3OTYyNiwiaWF0IjoxNjI1NTM2OTYwLjM3OTYyNn0.iJcoyDKXuJ0nB6PaJ7agsx3kV-x50au1Ob4YjYtHKbs HTTP/1.1" 200 -
[2021-07-06 07:36:32,958] {_internal.py:225} WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-07-06 07:36:32,959] {_internal.py:225} INFO -  * Running on http://192.168.1.243:666/ (Press CTRL+C to quit)
[2021-07-06 07:36:41,445] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:36:41] "POST /api/v1/signin?password=Wayward1240 HTTP/1.1" 200 -
[2021-07-06 07:36:44,935] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:36:44] "POST /api/v1/signin?password=Wayward1240 HTTP/1.1" 200 -
[2021-07-06 07:36:57,885] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:36:57] "POST /api/v1/signout?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBJZCI6IkhGUVpUNFM3UThaSlJIOTlEVTFGRFI4WDhLOUw2NlQwRUI3WjdNVlpXNUVYRVBDVDc1IiwiZXhwIjoxNjI1NTM5MDA0LjkzNDU2NiwiaWF0IjoxNjI1NTM3MjA0LjkzNDU2Nn0.-RES9jpBNbZq6HrUMx_SAzsszN6hIFy72kpnCH8AUDQ HTTP/1.1" 200 -
[2021-07-06 07:41:33,384] {_internal.py:225} WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-07-06 07:41:33,386] {_internal.py:225} INFO -  * Running on http://192.168.1.243:666/ (Press CTRL+C to quit)
[2021-07-06 07:41:37,238] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:41:37] "GET /api/ HTTP/1.1" 200 -
[2021-07-06 07:41:37,613] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:41:37] "[36mGET /api/swagger-ui-bundle.js HTTP/1.1[0m" 304 -
[2021-07-06 07:41:37,614] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:41:37] "[36mGET /api/swagger-ui.css HTTP/1.1[0m" 304 -
[2021-07-06 07:41:37,614] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:41:37] "[36mGET /api/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 -
[2021-07-06 07:41:37,800] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:41:37] "GET /static/swagger.json HTTP/1.1" 200 -
[2021-07-06 07:41:37,808] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:41:37] "GET /api/favicon-32x32.png HTTP/1.1" 200 -
[2021-07-06 07:41:47,460] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:41:47] "[31m[1mGET /api/v1/info HTTP/1.1[0m" 401 -
[2021-07-06 07:46:11,006] {_internal.py:225} WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-07-06 07:46:11,007] {_internal.py:225} INFO -  * Running on http://192.168.1.243:666/ (Press CTRL+C to quit)
[2021-07-06 07:46:15,633] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:46:15] "GET /api/ HTTP/1.1" 200 -
[2021-07-06 07:46:15,984] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:46:15] "[36mGET /api/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 -
[2021-07-06 07:46:15,984] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:46:15] "[36mGET /api/swagger-ui.css HTTP/1.1[0m" 304 -
[2021-07-06 07:46:15,985] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:46:15] "[36mGET /api/swagger-ui-bundle.js HTTP/1.1[0m" 304 -
[2021-07-06 07:46:16,171] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:46:16] "[36mGET /static/swagger.json HTTP/1.1[0m" 304 -
[2021-07-06 07:46:16,180] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:46:16] "[36mGET /api/favicon-32x32.png HTTP/1.1[0m" 304 -
[2021-07-06 07:46:50,838] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:46:50] "POST /api/v1/signin?password=Wayward1240 HTTP/1.1" 200 -
[2021-07-06 07:47:28,296] {database.py:53} INFO - Database Connected..........
[2021-07-06 07:47:28,297] {ftl.py:22} INFO - getAliasClient() Called.........
[2021-07-06 07:47:28,303] {database.py:63} INFO - Database Connection Closed.........
[2021-07-06 07:47:28,305] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:47:28] "GET /api/v1/aliases HTTP/1.1" 200 -
[2021-07-06 07:47:41,084] {database.py:53} INFO - Database Connected..........
[2021-07-06 07:47:41,084] {gravity.py:77} INFO - getWhiteAdList() Called.........
[2021-07-06 07:47:41,086] {database.py:63} INFO - Database Connection Closed.........
[2021-07-06 07:47:41,087] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:47:41] "GET /api/v1/whitelist HTTP/1.1" 200 -
[2021-07-06 07:48:03,080] {ftl.py:75} INFO - getFTL() Called.........
[2021-07-06 07:48:05,139] {ftlservice.py:66} INFO - Error connecting to FTLDNS (<class 'ConnectionRefusedError'>, ConnectionRefusedError(10061, 'No connection could be made because the target machine actively refused it', None, 10061, None), <traceback object at 0x000001DCA90D82C0>)
[2021-07-06 07:48:05,140] {ftlservice.py:68} INFO - Closing the connection......
[2021-07-06 07:48:05,142] {_internal.py:225} INFO - 192.168.1.243 - - [06/Jul/2021 07:48:05] "[35m[1mGET /api/v1/ftl/stats HTTP/1.1[0m" 500 -
[2021-07-10 05:21:01,148] {wasyncore.py:485} INFO - Serving on http://0.0.0.0:600
[2021-07-10 05:21:57,866] {wasyncore.py:485} INFO - Serving on http://127.0.0.1:600
[2021-07-10 05:22:35,136] {ftl.py:72} INFO - getFTL() Called.........
[2021-07-10 05:22:37,183] {ftlservice.py:63} INFO - Error connecting to FTLDNS (<class 'ConnectionRefusedError'>, ConnectionRefusedError(10061, 'No connection could be made because the target machine actively refused it', None, 10061, None), <traceback object at 0x0000013CC45BC280>)
[2021-07-10 05:22:37,184] {ftlservice.py:65} INFO - Closing the connection......
[2021-07-16 16:52:54,523] {wasyncore.py:485} INFO - Serving on http://127.0.0.1:5000
[2021-07-16 17:22:54,450] {wasyncore.py:485} INFO - Serving on http://127.0.0.1:5000
[2021-07-16 17:27:35,902] {wasyncore.py:485} INFO - Serving on http://127.0.0.1:5000
[2021-07-16 17:27:48,576] {ftl.py:72} INFO - getFTL() Called.........
[2021-07-16 17:27:48,577] {app.py:1454} ERROR - Exception on /api/v1/ftl/overtime [GET]
Traceback (most recent call last):
  File "/home/sammy/.local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sammy/.local/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sammy/.local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/sammy/.local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sammy/.local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/sammy/Documents/acumen-flask/v1/ftl.py", line 141, in getFTL
    response = sendRequestToFTL(message)
  File "/home/sammy/Documents/acumen-flask/v1/ftlservice.py", line 44, in sendRequestToFTL
    config = getFullFTLConfig()
  File "/home/sammy/Documents/acumen-flask/v1/ftlservice.py", line 35, in getFullFTLConfig
    currentConfig = getCurrentFTLConfig()
  File "/home/sammy/Documents/acumen-flask/v1/ftlservice.py", line 29, in getCurrentFTLConfig
    data = getData("pihole-FTL.conf", "=", True)
  File "/home/sammy/Documents/acumen-flask/v1/database.py", line 39, in getData
    config = open(fullpath(file))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\SaM AroRa\\\\Desktop\\\\DB\\\\pihole-FTL.conf'
[2021-07-16 17:33:23,715] {wasyncore.py:485} INFO - Serving on http://127.0.0.1:5000
[2021-07-16 17:33:29,621] {ftl.py:72} INFO - getFTL() Called.........
[2021-07-16 17:33:29,629] {ftlservice.py:63} INFO - Error connecting to FTLDNS (<class 'ConnectionRefusedError'>, ConnectionRefusedError(111, 'Connection refused'), <traceback object at 0x7fbcb608d6c0>)
[2021-07-16 17:33:29,629] {ftlservice.py:65} INFO - Closing the connection......
[2021-07-16 17:34:13,918] {ftl.py:72} INFO - getFTL() Called.........
[2021-07-16 17:34:13,924] {ftlservice.py:63} INFO - Error connecting to FTLDNS (<class 'ConnectionRefusedError'>, ConnectionRefusedError(111, 'Connection refused'), <traceback object at 0x7fbcb608d880>)
[2021-07-16 17:34:13,924] {ftlservice.py:65} INFO - Closing the connection......
[2021-07-16 17:34:22,942] {ftl.py:72} INFO - getFTL() Called.........
[2021-07-16 17:34:22,949] {ftlservice.py:63} INFO - Error connecting to FTLDNS (<class 'ConnectionRefusedError'>, ConnectionRefusedError(111, 'Connection refused'), <traceback object at 0x7fbcb608d7c0>)
[2021-07-16 17:34:22,949] {ftlservice.py:65} INFO - Closing the connection......
[2021-07-16 17:35:56,576] {wasyncore.py:485} INFO - Serving on http://127.0.0.1:5000
[2021-07-16 17:36:00,582] {ftl.py:72} INFO - getFTL() Called.........
[2021-07-16 17:36:00,586] {ftlservice.py:63} INFO - Error connecting to FTLDNS (<class 'socket.gaierror'>, gaierror(-2, 'Name or service not known'), <traceback object at 0x7fd53cc5b780>)
[2021-07-16 17:36:00,587] {ftlservice.py:65} INFO - Closing the connection......
